server:
  port: 9091
# SPRING PROFILES
spring:
  application:
    name: dubbo-provider-dev

# Dubbo Application
## The default value of dubbo.application.name is ${spring.application.name}
dubbo:
  application:
    name: dubbo-provider-dev
  scan:
    base-packages: com.example.dubbo.provider.serviceImpl
  protocols:
    rmi:
      name: rmi
      port: 1099
      serialization: hessian2
    dubbo:
      name: dubbo
      port: 20990
      server: netty
      client: netty
      codec: dubbo
      serialization: hessian2
      charset: UTF-8
      threadpool: fixed
      threads: 100
      queues: 0
      iothreads: 9
      buffer: 8192
      accepts: 1000
      payload: 1048576
    hessian:
      name: hessian
      port: 18888
      serialization: hessian2
      payload: 10485760
      charset: UTF-8
      server: jetty
  registries:
    zk:
      address: zookeeper://192.168.199.8:2181
      default: true
    redis:
      address: redis://192.168.199.7:6379

# logger
logging:
  config: classpath:logback.xml